# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  DEPLOY_BRANCH: deploy-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: 'x64'

      - name: Install and Build
        env:
          GOOGLE_ANALYTICS_KEY: G-XE1QMD9EVV
          MIRROR_DOWNLOAD_HOST: ${{ secrets.GHMIRROR_MIRROR_DOWNLOAD_HOST }}
          UPLOAD_FILE_HOST: ${{ secrets.GHMIRROR_UPLOAD_FILE_HOST }}
        run: |
          pip install -r requirements.txt
          sed -i "s|#beian|${{ secrets.BEIAN_ID }}|" mkdocs.yml
          mkdocs build -v

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          force_orphan: true
          publish_branch: ${{ env.DEPLOY_BRANCH }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 🚀 Deploying to gh-pages @ ${{ env.GITHUB_SHA }}

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www
            rm -rf XCPCIO
            git clone https://github.dup4.com/XCPCIO/XCPCIO.git -b ${{ env.DEPLOY_BRANCH }} --depth=1
